server:
  error:
    include-stacktrace: on_param
   
spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/anime?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
